// File:     DummyGame.cpp
//
// Author:   Kimberly Voll     *** Your name ALWAYS goes here
//           12345678          *** Your ID number ALWAYS goes here
//           kvoll             *** Your userID ALWAYS goes here
//           L1X               *** Your lab section ALWAYS goes here
//
// Modified: 2010 Sep 27   *** Add a new date if you modify the file!
//
// Defines the DummyGame (sample) class for assignment 1
//
// DO NOT EDIT THIS FILE
//

#include "DummyGame.hpp"

DummyGame::DummyGame () 
// Creates a DummyGame object and sets its name string
// @intput: none
// @output: A DummyGame object
{
	DummyGame::gameName_ = "DummyGame";
}

void DummyGame::runGame( Player* p ) 
// Runs the DummyGame game for player p
// @input: The current Player object
// @output: none
{
	cout << "\n\nIf this was a real game, it would be running right now!\n\n";
}

string DummyGame::getGameName() 
// Returns the name of the game as a string
// @input: none
// @output: The name of the game as a string
{
	return DummyGame::gameName_;
}
